### PR TITLE
Add -fcommon to mitigate a build error

### PR DESCRIPTION
**Pull request by legeana**

### CODE REVIEW

**Comment by legeana** [comment]
*.o CLI:
```
build uv@sha/src_unix_sysinfo-loadavg.c.o: c_COMPILER ../src/unix/sysinfo-loadavg.c
 DEPFILE = uv@sha/src_unix_sysinfo-loadavg.c.o.d
 ARGS = -Iuv@sha -I. -I.. -I../include -I../src -I../src/unix -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -g -fPIC -pthread -D_GNU_SOURCE -fcommon
```

The whole log:
```
$ mesonwrap review libuv --pull-request=4 --allow-no-license --export-sources=/tmp/123
Inspecting project libuv, branch 1.18.0.
Repo name valid: ☑
Branch name valid: ☑
Target branch is not master: ☑
Has readme.txt: ☑
Has LICENSE.build: ☒
Has upstream.wrap: ☑
Repo contains only buildsystem files: ☑
upstream.wrap has directory: ☑
upstream.wrap directory has no path separators: ☑
upstream.wrap has source_url: ☑
upstream.wrap has source_filename: ☑
upstream.wrap source_filename has no path separators: ☑
upstream.wrap has source_hash: ☑
upstream.wrap has source_url with version substring: ☑
Download URL works: ☑
Hash matches: ☑
upstream.wrap directory 'libuv-v1.18.0' exists: ☑
Patch merges with source: ☑
The Meson build system
Version: 0.54.2
Source dir: /tmp/tmphb6d4nsm/src/libuv-v1.18.0
Build dir: /tmp/tmphb6d4nsm/bin
Build type: native build
Project name: libuv
Project version: 1.18.0
C compiler for the host machine: cc (gcc 10.1.0 "cc (GCC) 10.1.0")
C linker for the host machine: cc ld.bfd 2.34.50.20200508
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments -fcommon: YES 
Fetching value of define "__ANDROID__" :  
Run-time dependency threads found: YES
Library m found: YES
Library dl found: YES
Library util found: YES
Build targets in project: 2

Found ninja-1.10.0 at /usr/bin/ninja
meson setup: ☑
ninja: Entering directory `/tmp/tmphb6d4nsm/bin'
[24/174] Compiling C object 'uv@sha/src_unix_linux-core.c.o'
../src/libuv-v1.18.0/src/unix/linux-core.c: In function ‘uv__io_poll’:
../src/libuv-v1.18.0/src/unix/linux-core.c:343:5: warning: converting a packed ‘struct uv__epoll_event’ pointer (alignment 1) to a ‘uv__io_t’ {aka ‘struct uv__io_s’} pointer (alignment 8) may result in an unaligned pointer value [-Waddress-of-packed-member]
  343 |     loop->watchers[loop->nwatchers] = (void*) events;
      |     ^~~~
In file included from ../src/libuv-v1.18.0/src/unix/internal.h:38,
                 from ../src/libuv-v1.18.0/src/unix/linux-core.c:27:
../src/libuv-v1.18.0/src/unix/linux-syscalls.h:90:8: note: defined here
   90 | struct uv__epoll_event {
      |        ^~~~~~~~~~~~~~~
In file included from ../src/libuv-v1.18.0/include/uv.h:62,
                 from ../src/libuv-v1.18.0/src/unix/linux-core.c:26:
../src/libuv-v1.18.0/include/uv-unix.h:93:8: note: defined here
   93 | struct uv__io_s {
      |        ^~~~~~~~
[145/174] Compiling C object 'uvtest@exe/test_test-thread.c.o'
In file included from ../src/libuv-v1.18.0/test/test-thread.c:23:
../src/libuv-v1.18.0/test/test-thread.c: In function ‘thread_check_stack’:
../src/libuv-v1.18.0/test/test-thread.c:220:15: warning: implicit declaration of function ‘pthread_getattr_np’; did you mean ‘pthread_attr_init’? [-Wimplicit-function-declaration]
  220 |   ASSERT(0 == pthread_getattr_np(pthread_self(), &attr));
      |               ^~~~~~~~~~~~~~~~~~
../src/libuv-v1.18.0/test/task.h:98:9: note: in definition of macro ‘ASSERT’
   98 |   if (!(expr)) {                                          \
      |         ^~~~
[173/174] Linking target uvtest
FAILED: uvtest 
cc  -o uvtest 'uvtest@exe/test_blackhole-server.c.o' 'uvtest@exe/test_dns-server.c.o' 'uvtest@exe/test_echo-server.c.o' 'uvtest@exe/test_run-tests.c.o' 'uvtest@exe/test_runner.c.o' 'uvtest@exe/test_test-active.c.o' 'uvtest@exe/test_test-async.c.o' 'uvtest@exe/test_test-async-null-cb.c.o' 'uvtest@exe/test_test-barrier.c.o' 'uvtest@exe/test_test-callback-order.c.o' 'uvtest@exe/test_test-callback-stack.c.o' 'uvtest@exe/test_test-close-fd.c.o' 'uvtest@exe/test_test-close-order.c.o' 'uvtest@exe/test_test-condvar.c.o' 'uvtest@exe/test_test-connection-fail.c.o' 'uvtest@exe/test_test-cwd-and-chdir.c.o' 'uvtest@exe/test_test-default-loop-close.c.o' 'uvtest@exe/test_test-delayed-accept.c.o' 'uvtest@exe/test_test-dlerror.c.o' 'uvtest@exe/test_test-eintr-handling.c.o' 'uvtest@exe/test_test-embed.c.o' 'uvtest@exe/test_test-emfile.c.o' 'uvtest@exe/test_test-env-vars.c.o' 'uvtest@exe/test_test-error.c.o' 'uvtest@exe/test_test-fail-always.c.o' 'uvtest@exe/test_test-fs-copyfile.c.o' 'uvtest@exe/test_test-fs-event.c.o' 'uvtest@exe/test_test-fs-poll.c.o' 'uvtest@exe/test_test-fs.c.o' 'uvtest@exe/test_test-fork.c.o' 'uvtest@exe/test_test-get-currentexe.c.o' 'uvtest@exe/test_test-get-loadavg.c.o' 'uvtest@exe/test_test-get-memory.c.o' 'uvtest@exe/test_test-get-passwd.c.o' 'uvtest@exe/test_test-getaddrinfo.c.o' 'uvtest@exe/test_test-gethostname.c.o' 'uvtest@exe/test_test-getnameinfo.c.o' 'uvtest@exe/test_test-getsockname.c.o' 'uvtest@exe/test_test-handle-fileno.c.o' 'uvtest@exe/test_test-homedir.c.o' 'uvtest@exe/test_test-hrtime.c.o' 'uvtest@exe/test_test-idle.c.o' 'uvtest@exe/test_test-ip4-addr.c.o' 'uvtest@exe/test_test-ip6-addr.c.o' 'uvtest@exe/test_test-ipc-send-recv.c.o' 'uvtest@exe/test_test-ipc.c.o' 'uvtest@exe/test_test-loop-handles.c.o' 'uvtest@exe/test_test-loop-alive.c.o' 'uvtest@exe/test_test-loop-close.c.o' 'uvtest@exe/test_test-loop-stop.c.o' 'uvtest@exe/test_test-loop-time.c.o' 'uvtest@exe/test_test-loop-configure.c.o' 'uvtest@exe/test_test-multiple-listen.c.o' 'uvtest@exe/test_test-mutexes.c.o' 'uvtest@exe/test_test-osx-select.c.o' 'uvtest@exe/test_test-pass-always.c.o' 'uvtest@exe/test_test-ping-pong.c.o' 'uvtest@exe/test_test-pipe-bind-error.c.o' 'uvtest@exe/test_test-pipe-connect-error.c.o' 'uvtest@exe/test_test-pipe-connect-multiple.c.o' 'uvtest@exe/test_test-pipe-connect-prepare.c.o' 'uvtest@exe/test_test-pipe-getsockname.c.o' 'uvtest@exe/test_test-pipe-pending-instances.c.o' 'uvtest@exe/test_test-pipe-sendmsg.c.o' 'uvtest@exe/test_test-pipe-server-close.c.o' 'uvtest@exe/test_test-pipe-close-stdout-read-stdin.c.o' 'uvtest@exe/test_test-pipe-set-non-blocking.c.o' 'uvtest@exe/test_test-pipe-set-fchmod.c.o' 'uvtest@exe/test_test-platform-output.c.o' 'uvtest@exe/test_test-poll.c.o' 'uvtest@exe/test_test-poll-close.c.o' 'uvtest@exe/test_test-poll-close-doesnt-corrupt-stack.c.o' 'uvtest@exe/test_test-poll-closesocket.c.o' 'uvtest@exe/test_test-poll-oob.c.o' 'uvtest@exe/test_test-process-title.c.o' 'uvtest@exe/test_test-queue-foreach-delete.c.o' 'uvtest@exe/test_test-ref.c.o' 'uvtest@exe/test_test-run-nowait.c.o' 'uvtest@exe/test_test-run-once.c.o' 'uvtest@exe/test_test-semaphore.c.o' 'uvtest@exe/test_test-shutdown-close.c.o' 'uvtest@exe/test_test-shutdown-eof.c.o' 'uvtest@exe/test_test-shutdown-twice.c.o' 'uvtest@exe/test_test-signal-multiple-loops.c.o' 'uvtest@exe/test_test-signal.c.o' 'uvtest@exe/test_test-socket-buffer-size.c.o' 'uvtest@exe/test_test-spawn.c.o' 'uvtest@exe/test_test-stdio-over-pipes.c.o' 'uvtest@exe/test_test-tcp-alloc-cb-fail.c.o' 'uvtest@exe/test_test-tcp-bind-error.c.o' 'uvtest@exe/test_test-tcp-bind6-error.c.o' 'uvtest@exe/test_test-tcp-close-accept.c.o' 'uvtest@exe/test_test-tcp-close-while-connecting.c.o' 'uvtest@exe/test_test-tcp-close.c.o' 'uvtest@exe/test_test-tcp-create-socket-early.c.o' 'uvtest@exe/test_test-tcp-connect-error-after-write.c.o' 'uvtest@exe/test_test-tcp-connect-error.c.o' 'uvtest@exe/test_test-tcp-connect-timeout.c.o' 'uvtest@exe/test_test-tcp-connect6-error.c.o' 'uvtest@exe/test_test-tcp-flags.c.o' 'uvtest@exe/test_test-tcp-open.c.o' 'uvtest@exe/test_test-tcp-read-stop.c.o' 'uvtest@exe/test_test-tcp-shutdown-after-write.c.o' 'uvtest@exe/test_test-tcp-unexpected-read.c.o' 'uvtest@exe/test_test-tcp-oob.c.o' 'uvtest@exe/test_test-tcp-write-to-half-open-connection.c.o' 'uvtest@exe/test_test-tcp-write-after-connect.c.o' 'uvtest@exe/test_test-tcp-writealot.c.o' 'uvtest@exe/test_test-tcp-write-fail.c.o' 'uvtest@exe/test_test-tcp-try-write.c.o' 'uvtest@exe/test_test-tcp-write-queue-order.c.o' 'uvtest@exe/test_test-thread-equal.c.o' 'uvtest@exe/test_test-thread.c.o' 'uvtest@exe/test_test-threadpool-cancel.c.o' 'uvtest@exe/test_test-threadpool.c.o' 'uvtest@exe/test_test-timer-again.c.o' 'uvtest@exe/test_test-timer-from-check.c.o' 'uvtest@exe/test_test-timer.c.o' 'uvtest@exe/test_test-tmpdir.c.o' 'uvtest@exe/test_test-tty.c.o' 'uvtest@exe/test_test-udp-alloc-cb-fail.c.o' 'uvtest@exe/test_test-udp-bind.c.o' 'uvtest@exe/test_test-udp-create-socket-early.c.o' 'uvtest@exe/test_test-udp-dgram-too-big.c.o' 'uvtest@exe/test_test-udp-ipv6.c.o' 'uvtest@exe/test_test-udp-multicast-interface.c.o' 'uvtest@exe/test_test-udp-multicast-interface6.c.o' 'uvtest@exe/test_test-udp-multicast-join.c.o' 'uvtest@exe/test_test-udp-multicast-join6.c.o' 'uvtest@exe/test_test-udp-multicast-ttl.c.o' 'uvtest@exe/test_test-udp-open.c.o' 'uvtest@exe/test_test-udp-options.c.o' 'uvtest@exe/test_test-udp-send-and-recv.c.o' 'uvtest@exe/test_test-udp-send-hang-loop.c.o' 'uvtest@exe/test_test-udp-send-immediate.c.o' 'uvtest@exe/test_test-udp-send-unreachable.c.o' 'uvtest@exe/test_test-udp-try-send.c.o' 'uvtest@exe/test_test-walk-handles.c.o' 'uvtest@exe/test_test-watcher-cross-stop.c.o' 'uvtest@exe/test_runner-unix.c.o' -Wl,--as-needed -Wl,--no-undefined -Wl,--start-group libuv.so -pthread -lutil -Wl,--end-group '-Wl,-rpath,$ORIGIN/' -Wl,-rpath-link,/tmp/tmphb6d4nsm/bin/
/usr/bin/ld: uvtest@exe/test_test-poll-closesocket.c.o:/tmp/tmphb6d4nsm/bin/../src/libuv-v1.18.0/test/test-poll-closesocket.c:28: multiple definition of `sock'; uvtest@exe/test_test-poll-close-doesnt-corrupt-stack.c.o:/tmp/tmphb6d4nsm/bin/../src/libuv-v1.18.0/test/test-poll-close-doesnt-corrupt-stack.c:35: first defined here
/usr/bin/ld: uvtest@exe/test_test-poll-closesocket.c.o:/tmp/tmphb6d4nsm/bin/../src/libuv-v1.18.0/test/test-poll-closesocket.c:29: multiple definition of `handle'; uvtest@exe/test_test-poll-close-doesnt-corrupt-stack.c.o:/tmp/tmphb6d4nsm/bin/../src/libuv-v1.18.0/test/test-poll-close-doesnt-corrupt-stack.c:36: first defined here
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
ninja test: ☒
```

**Review by darrinsmart — COMMENTED** [review]
I think c_args needs to be added to the uvtest() executable as well - its the tests that have the error.

**Comment by legeana** [comment]
Perfect, thank you!

**Comment by legeana** [comment]
```
$ mesonwrap review libuv --pull-request=4 --allow-no-license --export-sources=/tmp/1234
Inspecting project libuv, branch 1.18.0.
Repo name valid: ☑
Branch name valid: ☑
Target branch is not master: ☑
Has readme.txt: ☑
Has LICENSE.build: ☒
Has upstream.wrap: ☑
Repo contains only buildsystem files: ☑
upstream.wrap has directory: ☑
upstream.wrap directory has no path separators: ☑
upstream.wrap has source_url: ☑
upstream.wrap has source_filename: ☑
upstream.wrap source_filename has no path separators: ☑
upstream.wrap has source_hash: ☑
upstream.wrap has source_url with version substring: ☑
Download URL works: ☑
Hash matches: ☑
upstream.wrap directory 'libuv-v1.18.0' exists: ☑
Patch merges with source: ☑
The Meson build system
Version: 0.54.2
Source dir: /tmp/tmpenbvxlx_/src/libuv-v1.18.0
Build dir: /tmp/tmpenbvxlx_/bin
Build type: native build
Project name: libuv
Project version: 1.18.0
C compiler for the host machine: cc (gcc 10.1.0 "cc (GCC) 10.1.0")
C linker for the host machine: cc ld.bfd 2.34.50.20200508
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments -fcommon: YES 
Fetching value of define "__ANDROID__" :  
Run-time dependency threads found: YES
Library m found: YES
Library dl found: YES
Library util found: YES
Build targets in project: 2

Found ninja-1.10.0 at /usr/bin/ninja
meson setup: ☑
ninja: Entering directory `/tmp/tmpenbvxlx_/bin'
[24/174] Compiling C object 'uv@sha/src_unix_linux-core.c.o'
../src/libuv-v1.18.0/src/unix/linux-core.c: In function ‘uv__io_poll’:
../src/libuv-v1.18.0/src/unix/linux-core.c:343:5: warning: converting a packed ‘struct uv__epoll_event’ pointer (alignment 1) to a ‘uv__io_t’ {aka ‘struct uv__io_s’} pointer (alignment 8) may result in an unaligned pointer value [-Waddress-of-packed-member]
  343 |     loop->watchers[loop->nwatchers] = (void*) events;
      |     ^~~~
In file included from ../src/libuv-v1.18.0/src/unix/internal.h:38,
                 from ../src/libuv-v1.18.0/src/unix/linux-core.c:27:
../src/libuv-v1.18.0/src/unix/linux-syscalls.h:90:8: note: defined here
   90 | struct uv__epoll_event {
      |        ^~~~~~~~~~~~~~~
In file included from ../src/libuv-v1.18.0/include/uv.h:62,
                 from ../src/libuv-v1.18.0/src/unix/linux-core.c:26:
../src/libuv-v1.18.0/include/uv-unix.h:93:8: note: defined here
   93 | struct uv__io_s {
      |        ^~~~~~~~
[145/174] Compiling C object 'uvtest@exe/test_test-thread.c.o'
In file included from ../src/libuv-v1.18.0/test/test-thread.c:23:
../src/libuv-v1.18.0/test/test-thread.c: In function ‘thread_check_stack’:
../src/libuv-v1.18.0/test/test-thread.c:220:15: warning: implicit declaration of function ‘pthread_getattr_np’; did you mean ‘pthread_attr_init’? [-Wimplicit-function-declaration]
  220 |   ASSERT(0 == pthread_getattr_np(pthread_self(), &attr));
      |               ^~~~~~~~~~~~~~~~~~
../src/libuv-v1.18.0/test/task.h:98:9: note: in definition of macro ‘ASSERT’
   98 |   if (!(expr)) {                                          \
      |         ^~~~
[173/174] Running all tests.
1/1 uvtest TIMEOUT        30.01s

Ok:                 0   
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            1   


The output from the failed tests:

1/1 uvtest TIMEOUT        30.01s

--- command ---
13:45:07 /tmp/tmpenbvxlx_/bin/uvtest
--- Listing only the last 100 lines from a long log. ---
# uv_os_getpid: 1594470
# uv_os_getppid: 1594469
ok 2 - active
ok 3 - async
ok 4 - async_null_cb
ok 5 - async_ref
ok 6 - barrier_1
ok 7 - barrier_2
ok 8 - barrier_3
ok 9 - callback_stack
ok 10 - check_ref
ok 11 - close_fd
ok 12 - close_order
ok 13 - closed_fd_events
ok 14 - condvar_1
ok 15 - condvar_2
ok 16 - condvar_3
ok 17 - condvar_4
ok 18 - condvar_5
ok 19 - connection_fail
ok 20 - connection_fail_doesnt_auto_close
ok 21 - cwd_and_chdir
ok 22 - default_loop_close
ok 23 - delayed_accept
ok 24 - dlerror
ok 25 - eintr_handling
ok 26 - embed
ok 27 - emfile
ok 28 - env_vars
ok 29 - error_message
ok 30 - fork_fs_events_child
ok 31 - fork_fs_events_child_dir
ok 32 - fork_fs_events_file_parent_child
ok 33 - fork_signal_to_child
ok 34 - fork_signal_to_child_closed
ok 35 - fork_socketpair
ok 36 - fork_socketpair_started
ok 37 - fork_threadpool_queue_work_simple
ok 38 - fork_timer
ok 39 - fs_access
ok 40 - fs_async_dir
ok 41 - fs_async_sendfile
ok 42 - fs_chmod
ok 43 - fs_chown
not ok 44 - fs_copyfile
# exit code 134
# Output from process `fs_copyfile`:
# Assertion failed in ../src/libuv-v1.18.0/test/test-fs-copyfile.c on line 120: r == 0
ok 45 - fs_event_close_in_callback
ok 46 - fs_event_close_with_pending_event
ok 47 - fs_event_error_reporting
ok 48 - fs_event_getpath
ok 49 - fs_event_immediate_close
ok 50 - fs_event_no_callback_after_close
ok 51 - fs_event_no_callback_on_close
ok 52 - fs_event_ref
ok 53 - fs_event_start_and_close
ok 54 - fs_event_watch_dir
ok 55 - fs_event_watch_dir_recursive # SKIP Recursive directory watching not supported on this platform.
ok 56 - fs_event_watch_file
ok 57 - fs_event_watch_file_current_dir
ok 58 - fs_event_watch_file_exact_path
not ok 59 - fs_event_watch_file_twice
# exit code 134
# Output from process `fs_event_watch_file_twice`:
# Assertion failed in ../src/libuv-v1.18.0/test/test-fs-event.c on line 576: 0 == uv_fs_event_start(watchers + 0, fail_cb, path, 0)
ok 60 - fs_event_watch_invalid_path
ok 61 - fs_file_async
ok 62 - fs_file_loop
ok 63 - fs_file_nametoolong
ok 64 - fs_file_noent
ok 65 - fs_file_open_append
ok 66 - fs_file_pos_after_op_with_offset
ok 67 - fs_file_sync
ok 68 - fs_file_write_null_buffer
ok 69 - fs_fstat
ok 70 - fs_futime
ok 71 - fs_mkdtemp
ok 72 - fs_null_req
ok 73 - fs_open_dir
ok 74 - fs_poll
ok 75 - fs_poll_getpath
ok 76 - fs_poll_ref
ok 77 - fs_read_file_eof
ok 78 - fs_read_write_null_arguments
ok 79 - fs_readlink
ok 80 - fs_realpath
ok 81 - fs_rename_to_existing_file
ok 82 - fs_scandir_empty_dir
not ok 83 - fs_scandir_file
# exit code 134
# Output from process `fs_scandir_file`:
# Assertion failed in ../src/libuv-v1.18.0/test/test-fs.c on line 2373: r == UV_ENOTDIR
ok 84 - fs_scandir_non_existent_dir
ok 85 - fs_stat_missing_path
ok 86 - fs_symlink
ok 87 - fs_symlink_dir
ok 88 - fs_unlink_readonly
-------

Full log written to /tmp/tmpenbvxlx_/bin/meson-logs/testlog.txt
FAILED: meson-test 
/usr/bin/meson test --no-rebuild --print-errorlogs
ninja: build stopped: subcommand failed.
ninja test: ☒
```

```
$ grep 'not ok' -A 5 /tmp/1234/libuv-v1.18.0/builddir/meson-logs/testlog.txt
not ok 44 - fs_copyfile
# exit code 6
# Output from process `fs_copyfile`:
# Assertion failed in ../test/test-fs-copyfile.c on line 120: r == 0
ok 45 - fs_event_close_in_callback
ok 46 - fs_event_close_with_pending_event
--
not ok 59 - fs_event_watch_file_twice
# exit code 6
# Output from process `fs_event_watch_file_twice`:
# Assertion failed in ../test/test-fs-event.c on line 576: 0 == uv_fs_event_start(watchers + 0, fail_cb, path, 0)
ok 60 - fs_event_watch_invalid_path
ok 61 - fs_file_async
--
not ok 83 - fs_scandir_file
# exit code 6
# Output from process `fs_scandir_file`:
# Assertion failed in ../test/test-fs.c on line 2373: r == UV_ENOTDIR
ok 84 - fs_scandir_non_existent_dir
ok 85 - fs_stat_missing_path
--
not ok 142 - pipe_connect_to_file
# exit code 6
# Output from process `pipe_connect_to_file`:
# Assertion failed in ../test/test-pipe-connect-error.c on line 53: status == UV_ENOTSOCK || status == UV_ECONNREFUSED
ok 143 - pipe_getsockname
ok 144 - pipe_getsockname_abstract
```

The same happens on the original branch though, so I am leaving it as is. I am also increasing the test timeout to 5min.

**Pull request merged**
